name: flutter_talk
description: examples and topics in Flutter talk meetup
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ^3.3.2

dependencies:
  flutter:
    sdk: flutter
  imager: ^1.0.0
  rxdart: ^0.27.0
  lifecycle_aware_state: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
